# Generated by Django 3.2.8 on 2022-01-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220117_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='dubject',
            new_name='subject',
        ),
    ]
